name: Run Docker Container
on: [push]

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    #
    #- name: Set up Docker
    #  run: |
    #    sudo apt-get update
    #    sudo apt-get install -y docker.io

    - name: Run Docker Container
      run: |
        docker pull liurenjie/ubuntu:mail_20240109
        docker run liurenjie/ubuntu:mail_20240109 /bin/bash -c 'echo "Hello from ${HOSTNAME} mail test" | mail -s "Hello from ${HOSTNAME} mail test" anlrj@qq.com'
		
