name: Run_Docker_Container
on: [push]

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    #
    #- name: Set up Docker
    #  run: |
    #    sudo apt-get update
    #    sudo apt-get install -y docker.io

     - name: Run Docker Container
       run: |
         docker pull xxxxxx
         docker run xxxxxxxxxx /bin/bash -c 'command_here'

