name: Send email when pushed
on: [push]
jobs:
  sending-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3.6.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Message from github actions.
          to: anlrj@qq.com
          from: liurenjiemessage
          secure: true
          body: workflow for ${{github.repository}} completed successfully!
